---
# tasks file for backend-deploy
- name: Copy be template
  become: true
  copy:
    src: templates/be-template.j2
    dest: /etc/nginx/sites-available/backend

- name: Link to site-enabled
  file:
    src: /etc/nginx/sites-available/backend
    dest: /etc/nginx/sites-enabled/backend
    state: link
  become: true
  notify: Restart Nginx

- name: start php-fpm
  shell: "./php8.1-fpm start"
  become: yes
  args:
    chdir: /etc/init.d/

- name: Curl result
  uri:
    url: "http://localhost:8000"
    method: GET
    return_content: yes
  register: result

- name: Display response
  debug:
    var: result.content