- hosts: localhost
  gather_facts: true
  become: true
  # vars_files:
  #   - env/vars.yml

  roles:
    # - roles/backend-build
    # - roles/backend-migrate
    - roles/backend-deploy
    - roles/frontend-deploy